### Data Preparation

### 一、张量操作

In [1]:
import torch
import os 
import pandas as pd


In [ ]:
#张量创建、形状和元素数
x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel())
print(x.reshape(3, 4))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
# 创建二维列表
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# 基本运算
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print(x + y)
print(x * y)
print(x / y)
print(x - y)
print(x ** y)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([-3, -3, -3])
tensor([  1,  32, 729])


In [ ]:
x = torch.exp(x)
print(x)

tensor([ 2.7183,  7.3891, 20.0855])


In [ ]:
# 张量拼接、比较和求和
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2.0, 1.0, 1.0, 0.0], [2.0, 1.0, 1.0, 0.0], [2.0, 1.0, 1.0, 0.0]])
print(x)
print(y)
print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))
print(x == y)
print(torch.sum(x))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 1., 0.],
        [2., 1., 1., 0.],
        [2., 1., 1., 0.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  1.,  0.],
        [ 2.,  1.,  1.,  0.],
        [ 2.,  1.,  1.,  0.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  1.,  0.],
        [ 4.,  5.,  6.,  7.,  2.,  1.,  1.,  0.],
        [ 8.,  9., 10., 11.,  2.,  1.,  1.,  0.]])
tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


In [8]:
#张量的索引和切片
x = torch.arange(3, dtype=torch.float32)
y = torch.arange(3, dtype=torch.float32)
print(x + y)

print(x[2])
x[2] = 10
print(x)

z = x[1:3]
print(z)
z[:] = 200
print(z)
print(x)

x[:] = x + y
print(x)



tensor([0., 2., 4.])
tensor(2.)
tensor([ 0.,  1., 10.])
tensor([ 1., 10.])
tensor([200., 200.])
tensor([  0., 200., 200.])
tensor([  0., 201., 202.])


In [11]:
# 张量与numpy数组转换
a = x.numpy()
print(a)
b = torch.from_numpy(a)
print(b)


[  0. 201. 202.]
tensor([  0., 201., 202.])


In [10]:
#标量张量的取值
a = torch.tensor([3.5])
print(a)
print(a.item(), float(a), int(a))

tensor([3.5000])
3.5 3.5 3


#### 二、数据预处理

In [12]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500.0\n')
    f.write('2,NA,106000.0\n')
    f.write('4,NA,178100.0\n')
    f.write('NA,NA,140000.0\n')

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley     Price
0       NaN  Pave  127500.0
1       2.0   NaN  106000.0
2       4.0   NaN  178100.0
3       NaN   NaN  140000.0


In [15]:
# 拆分输入输出
input_data, output_data = data.iloc[:, 0:2], data.iloc[:, 2]
print(input_data.shape, output_data.shape)
print(input_data.head())
print(output_data.head())

(4, 2) (4,)
   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
0    127500.0
1    106000.0
2    178100.0
3    140000.0
Name: Price, dtype: float64


In [16]:
# 处理缺失值
num_rooms_mean = input_data['NumRooms'].mean()
input_data['NumRooms'] = input_data['NumRooms'].fillna(num_rooms_mean)
print(input_data.head())

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [18]:
# 处理类别型变量并确保输出为数值类型
input_encoded = pd.get_dummies(input_data, dummy_na=True)
input_encoded = input_encoded.astype('float32')  
print(input_encoded)

   NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0


In [19]:
# 转化为张量
x = torch.tensor(input_encoded.values)
y = torch.tensor(output_data.values.astype('float32')) 
print(x)
print(y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]])
tensor([127500., 106000., 178100., 140000.])
